AWSTemplateFormatVersion: '2010-09-09'
Description: Environement AWS Cloud9 pour l'onboarding IPPON

Parameters:

  TeamName:
    Description: Please specify the team name.
    Type:        String
    Default:     master

Resources:

  C9IDE:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      Name: !Sub 'onboarding-ippon-${TeamName}-cloud9'
      Description: !Sub '${TeamName} Cloud9 IDE'
      AutomaticStopTimeMinutes: '60'
      InstanceType: 't2.medium'
      OwnerArn: !Sub 'arn:aws:iam::${AWS::AccountId}:user/${TeamName}'
      # Repositories:
      #   - RepositoryUrl:
      #     PathComponent:


Outputs:

  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
      - ''
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
        - !Ref 'C9IDE'

